const dateformat = require('dateformat')
const { get } = require('../common/apiConnector')

const transform = async ({ id, autoIncrement, description, descriptionLong, price, name, ean, cover, stock, datasheet, createdAt, updatedAt, attributeIds }, categories, gallery) => ({
  "entity_type_id": 4,
  "attribute_set_id": 11,
  "type_id": "simple",
  "sku": ean ? ean : id,
  "has_options": 0,
  "required_options": 0,
  "created_at": dateformat(createdAt, 'yyyy-mm-dd H:mm:s'),
  "updated_at": dateformat(createdAt, 'yyyy-mm-dd H:mm:s'),
  "color": null,
  "size": null,
  "jewelry_type": null,
  "status": 1,
  "accessories_size": null,
  "visibility": 4,
  "tax_class_id": 2,
  "is_recurring": false,
  "description": description,
  "meta_keyword": null,
  "short_description": description,
  "custom_layout_update": null,
  "name": name,
  "meta_title": null,
  "image": cover ? cover.media.url : (gallery.length ? gallery[0].image : ''),
  "custom_design": null,
  "gift_message_available": null,
  "small_image":  cover ? cover.media.url : (gallery.length ? gallery[0].image : ''),
  "gift_wrapping_available": 0,
  "meta_description": null,
  "thumbnail":  cover ? cover.media.url : (gallery.length ? gallery[0].image : ''),
  "media_gallery": gallery.length ? gallery : (cover ? [cover.media.url] : []),
  "gallery": gallery.length ? gallery : (cover ? [cover.media.url] : []),
  "page_layout": "three_columns",
  "options_container": "container1",
  "url_key": autoIncrement.toString(),
  "country_of_manufacture": null,
  "msrp_enabled": 2,
  "msrp_display_actual_price_type": 4,
  "url_path": `${autoIncrement}.html`,
  "image_label": null,
  "small_image_label": null,
  "thumbnail_label": null,
  "gift_wrapping_price": null,
  "weight": 1,
  "price": price.gross,
  "final_price": price.gross,
  "price_incl_tax": price.gross,
  "final_price_incl_tax": price.gross,
  "special_price": null,
  "msrp": null,
  "custom_design_from": null,
  "custom_design_to": null,
  "news_from_date": null,
  "news_to_date": null,
  "special_from_date": null,
  "special_to_date": null,
  "is_salable": true,
  "stock_item": {},
  "id": autoIncrement,
  "category": categories,
  "category_ids": categories.map(category => category.category_id),
  "stock":{
      "is_in_stock": !!stock
  }
})

module.exports = transform