const dateformat = require('dateformat')
const { get } = require('../common/apiConnector')

const configurable = async ({ id, autoIncrement, description, descriptionLong, price, name, ean, cover, stock, datasheet, createdAt, updatedAt, attributeIds }, categories, gallery) => ({
  "entity_type_id": 4,
  "attribute_set_id": 11,
  "type_id": "configurable",
  "sku": ean ? ean : id,
  "has_options": 1,
  "required_options": 1,
  "created_at": dateformat(createdAt, 'yyyy-mm-dd H:mm:s'),
  "updated_at": dateformat(createdAt, 'yyyy-mm-dd H:mm:s'),
  "status": 1,
  "visibility": 4,
  "tax_class_id": 2,
  "is_recurring": false,
  "description": description,
  "meta_keyword": null,
  "short_description": description,
  "custom_layout_update": null,
  "name": name,
  "meta_title": null,
  "image": cover ? cover.media.url : (gallery.length ? gallery[0].image : ''),
  "custom_design": null,
  "gift_message_available": null,
  "small_image":  cover ? cover.media.url : (gallery.length ? gallery[0].image : ''),
  "gift_wrapping_available": 0,
  "meta_description": null,
  "thumbnail":  cover ? cover.media.url : (gallery.length ? gallery[0].image : ''),
  "media_gallery": gallery.length ? gallery : (cover ? [cover.media.url] : []),
  "gallery": gallery.length ? gallery : (cover ? [cover.media.url] : []),
  "page_layout": "three_columns",
  "options_container": "container1",
  "url_key": autoIncrement.toString(),
  "country_of_manufacture": null,
  "msrp_enabled": 2,
  "msrp_display_actual_price_type": 4,
  "url_path": `${autoIncrement}.html`,
  "image_label": null,
  "small_image_label": null,
  "thumbnail_label": null,
  "gift_wrapping_price": null,
  "weight": 1,
  "price": price.gross,
  "final_price": price.gross,
  "price_incl_tax": price.gross,
  "final_price_incl_tax": price.gross,
  "special_price": null,
  "msrp": null,
  "custom_design_from": null,
  "custom_design_to": null,
  "news_from_date": null,
  "news_to_date": null,
  "special_from_date": null,
  "special_to_date": null,
  "is_salable": true,
  "stock_item": {},
  "id": autoIncrement,
  "category": categories,
  "category_ids": categories.map(category => category.category_id),
  "stock": {
    "item_id": autoIncrement,
    "product_id": autoIncrement,
    "stock_id": 1,
    "qty": 10,
    "is_in_stock": true,
    "is_qty_decimal": false,
    "show_default_notification_message": false,
    "use_config_min_qty": true,
    "min_qty": 0,
    "use_config_min_sale_qty": 1,
    "min_sale_qty": 1,
    "use_config_max_sale_qty": true,
    "max_sale_qty": 10000,
    "use_config_backorders": true,
    "backorders": 0,
    "use_config_notify_stock_qty": true,
    "notify_stock_qty": 1,
    "use_config_qty_increments": true,
    "qty_increments": 0,
    "use_config_enable_qty_inc": true,
    "enable_qty_increments": false,
    "use_config_manage_stock": true,
    "manage_stock": true,
    "low_stock_date": null,
    "is_decimal_divided": false,
    "stock_status_changed_auto": 0
},
  
})


const simple = async ({ id, autoIncrement, description, descriptionLong, price, name, ean, cover, stock, datasheet, createdAt, updatedAt, attributeIds }) => ({
  "id": autoIncrement,
  "sku": id,
  "name": name ? name : `${autoIncrement}`,
  "attribute_set_id": 4,
  "price": price,
  "status": 1,
  "visibility": 1,
  "type_id": "simple",
  "created_at": dateformat(createdAt, 'yyyy-mm-dd H:mm:s'),
  "updated_at": dateformat(createdAt, 'yyyy-mm-dd H:mm:s'),
  "weight": 1,
  "product_links": [],
  "tier_prices": [],
  "custom_attributes": null,
  "price": price.gross,
  "final_price": price.gross,
  "price_incl_tax": price.gross,
  "final_price_incl_tax": price.gross,
  "description": " ",
  "special_from_date": null,
  "image": "",
  "small_image": "",
  "thumbnail": "",
  "color": null,
  "size": null,
  "news_from_date": null,
  "custom_design_from":null,
  "category_ids": [],
  "options_container": "container2",
  "has_options": "0",
  "url_key": id,
  "tax_class_id": "2",
  "zoom_image": "",
  "links": {},
  "media_gallery": [],
  "category": [],
  "priceTax": 0,
  "priceInclTax": price.gross,
  "specialPriceTax": 0,
  "specialPriceInclTax": 0,
  "stock": {
    "item_id": autoIncrement,
    "product_id": autoIncrement,
    "stock_id": 1,
    "qty": 10,
    "is_in_stock": true
  },
})

module.exports = {
  configurable,
  simple
}